[package]
name = "confible"
version = "0.1.0"
authors = ["Simon Jürgensmeyer <simon.juergensmeyer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.124"
serde_derive = "1.0.124"
toml = "0.5.8"