{
 "title": "Netatmo VM",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "Temperature_value" }
   ]
  },
  {
   "title": "Indoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Temperature_value{db=\"netatmo\", module=\"Indoor\"}"
    }
   ]
  },
  {
   "title": "Outdoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Temperature_value{db=\"netatmo\", module=\"Outdoor\"}"
    }
   ]
  },
  {
   "title": "Humidity Indoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Humidity_value{db=\"netatmo\", module=\"Indoor\"}"
    }
   ]
  },
  {
   "title": "Humidity Outdoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Humidity_value{db=\"netatmo\", module=\"Outdoor\"}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CO2_value{db=\"netatmo\", module=\"Indoor\"}"
    }
   ]
  },
  {
   "title": "Rain (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "Rain_value{db=\"netatmo\", module=\"Rain\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "Humidity_value" }
   ]
  },
  {
   "title": "Noise",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Noise_value{db=\"netatmo\", module=\"Indoor\"}"
    }
   ]
  },
  {
   "title": "WiFi Status",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wifi_status_value{db=\"netatmo\"}"
    }
   ]
  },
  {
   "title": "Outdoor RF",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rf_status_value{db=\"netatmo\",module=\"Outdoor\"}"
    }
   ]
  },
  {
   "title": "Outdoor Battery",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_vp_value{db=\"netatmo\",module=\"Outdoor\"}"
    }
   ]
  },
  {
   "title": "Rain RF",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rf_status_value{db=\"netatmo\",module=\"Rain\"}"
    }
   ]
  },
  {
   "title": "Rain Battery",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_vp_value{db=\"netatmo\", module=\"Rain\"}"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    { "expr": "Noise_value" }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "CO2_value" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    { "expr": "AbsolutePressure_value" },
    { "expr": "Pressure_value" }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    { "expr": "Rain_value" }
   ]
  },
  {
   "title": "RF / WiFi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rf_status_value" }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "battery_vp_value" }
   ]
  }
 ]
}