{
 "title": "Netatmo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indoor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Indoor" }
     ]
    }
   ]
  },
  {
   "title": "Outdoor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Humidity Indoor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Indoor" }
     ]
    }
   ]
  },
  {
   "title": "Humidity Outdoor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "lengthmm",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Rain",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "ppm",
   "valueName": "current",
   "targets": [
    {
     "measurement": "CO2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 } },
  {
   "title": "WiFi Status",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain Battery",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "measurement": "battery_vp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Rain" }
     ]
    }
   ]
  },
  {
   "title": "Outdoor Battery",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "measurement": "battery_vp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Rain RF",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "measurement": "rf_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Rain" }
     ]
    }
   ]
  },
  {
   "title": "Outdoor RF",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "measurement": "rf_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "Outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "measurement": "AbsolutePressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "CO2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "measurement": "Rain",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Noise",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "measurement": "Noise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "measurement": "temp_trend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "battery_vp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RF / WiFi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "rf_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}