{
 "title": "Netatmo Postgres",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM temperature\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Indoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM temperature\nWHERE  $__timeFilter(\"time\") AND module='indoor'"
    }
   ]
  },
  {
   "title": "Outdoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM temperature\nWHERE  $__timeFilter(\"time\") AND module='outdoor'\n"
    }
   ]
  },
  {
   "title": "Humidity Indoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM humidity\nWHERE  $__timeFilter(\"time\") AND module='indoor'"
    }
   ]
  },
  {
   "title": "Humidity Outdoor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM humidity\nWHERE  $__timeFilter(\"time\") AND module='outdoor'"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM co2\nWHERE  $__timeFilter(\"time\") AND module='indoor'"
    }
   ]
  },
  {
   "title": "Rain (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM rain\nWHERE  $__timeFilter(\"time\") AND module='rain'"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM humidity\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM noise\nWHERE  $__timeFilter(\"time\") AND module='indoor'"
    }
   ]
  },
  {
   "title": "WiFi Status",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM wifi_status\nWHERE  $__timeFilter(\"time\") AND module='indoor'"
    }
   ]
  },
  {
   "title": "Outdoor RF",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM rf_status\nWHERE  $__timeFilter(\"time\") AND module='outdoor'"
    }
   ]
  },
  {
   "title": "Outdoor Battery",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM battery_vp\nWHERE  $__timeFilter(\"time\") AND module='outdoor'"
    }
   ]
  },
  {
   "title": "Rain RF",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM rf_status\nWHERE  $__timeFilter(\"time\") AND module='rain'"
    }
   ]
  },
  {
   "title": "Rain Battery",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value AS \"value\"\nFROM battery_vp\nWHERE  $__timeFilter(\"time\") AND module='rain'"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM noise\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM co2\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM absolutepressure\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM pressure\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM rain\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RF / WiFi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM rf_status\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  module AS metric,\n  value\nFROM battery_vp\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  }
 ]
}