.PHONY: build-api
build-api:
	docker build api -t ghcr.io/sj14/netatmo-api:latest

.PHONY: push-api
push-api:
	docker push ghcr.io/sj14/netatmo-api:latest

.PHONY: build-csv
build-csv:
	docker build csv -t ghcr.io/sj14/netatmo-csv:latest

.PHONY: push-csv
push-csv:
	docker push ghcr.io/sj14/netatmo-csv:latest

